### ISSUE TITLE
Just got a lot of errors from the API

### ISSUE THREAD

**Issue by DragosPV** [discordjs/discord-api-types#578]
```
C:\Users\HOST\Documents\GitHub\life-pv\node_modules\@discordjs\rest\dist\lib\handlers\SequentialHandler.cjs:280
      throw new HTTPError.HTTPError(res.constructor.name, status, method, url, requestData);
            ^

Object
    at SequentialHandler.runRequest (C:\Users\HOST\Documents\GitHub\life-pv\node_modules\@discordjs\rest\dist\lib\handlers\SequentialHandler.cjs:280:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SequentialHandler.runRequest (C:\Users\HOST\Documents\GitHub\life-pv\node_modules\@discordjs\rest\dist\lib\handlers\SequentialHandler.cjs:162:16)
    at async SequentialHandler.queueRequest (C:\Users\HOST\Documents\GitHub\life-pv\node_modules\@discordjs\rest\dist\lib\handlers\SequentialHandler.cjs:99:14)
    at async REST.request (C:\Users\HOST\Documents\GitHub\life-pv\node_modules\@discordjs\rest\dist\lib\REST.cjs:52:22)
    at async MessageManager.edit (C:\Users\HOST\Documents\GitHub\life-pv\node_modules\discord.js\src\managers\MessageManager.js:166:15)
    at async Object.success (C:\Users\HOST\Documents\GitHub\life-pv\things\info.js:287:13) {
  status: 502,
  method: 'PATCH',
  url: 'https://discord.com/api/v10/channels/905786048871813150/messages/993439280636624926',
  requestBody: {
    files: [],
    json: {
      content: undefined,
      tts: false,
      nonce: undefined,
      embeds: [
        {
          title: ' ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ 🐦Life Romania - Since 2020🐦\n' +
            ' ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ Live Info',
          color: 12648192,
          image: { url: 'https://i.imgur.com/tAm48CY.png' },
          fields: [
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object]
          ]
        },
        {
          color: 12648192,
          image: { url: 'https://i.imgur.com/tAm48CY.png' },
          fields: [
            [Object], [Object],
            [Object], [Object],
            [Object], [Object],
            [Object]
          ]
        },
        {
          color: 12648192,
          image: { url: 'https://i.imgur.com/tAm48CY.png' },
          fields: [ [Object], [Object], [Object], [Object] ]
        },
        {
          color: 12648192,
          image: { url: 'https://i.imgur.com/tAm48CY.png' },
          fields: [
            [Object], [Object],
            [Object], [Object],
            [Object], [Object],
            [Object], [Object],
            [Object], [Object],
            [Object]
          ]
        },
        {
          color: 12648192,
          image: { url: 'https://i.imgur.com/tAm48CY.png' },
          fields: [ [Object], [Object], [Object] ]
        },
        {
          color: 12648192,
          image: { url: 'https://i.imgur.com/tAm48CY.png' },
          fields: [ [Object], [Object], [Object], [Object] ]
        },
        {
          color: 12648192,
          image: { url: 'https://i.imgur.com/tAm48CY.png' },
          fields: [ [Object], [Object], [Object], [Object] ]
        },
        {
          color: 12648192,
          image: { url: 'https://i.imgur.com/tAm48CY.png' },
          fields: [ [Object], [Object], [Object], [Object] ]
        },
        {
          color: 12648192,
          image: { url: 'https://i.imgur.com/tAm48CY.png' },
          fields: [
            [Object], [Object],
            [Object], [Object],
            [Object], [Object],
            [Object], [Object],
            [Object], [Object]
          ]
        }
      ],
      components: undefined,
      username: undefined,
      avatar_url: undefined,
      allowed_mentions: undefined,
      flags: 0,
      message_reference: undefined,
      attachments: undefined,
      sticker_ids: undefined
    }
  }
}
Object
    at SequentialHandler.runRequest (C:\Users\HOST\Documents\GitHub\life-pv\node_modules\@discordjs\rest\dist\lib\handlers\SequentialHandler.cjs:280:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SequentialHandler.runRequest (C:\Users\HOST\Documents\GitHub\life-pv\node_modules\@discordjs\rest\dist\lib\handlers\SequentialHandler.cjs:162:16)
    at async SequentialHandler.queueRequest (C:\Users\HOST\Documents\GitHub\life-pv\node_modules\@discordjs\rest\dist\lib\handlers\SequentialHandler.cjs:99:14)
    at async REST.request (C:\Users\HOST\Documents\GitHub\life-pv\node_modules\@discordjs\rest\dist\lib\REST.cjs:52:22) {
  status: 502,
  method: 'PUT',
  url: 'https://discord.com/api/v10/applications/944592494337876028/guilds/770003066467778590/commands',
  requestBody: {
    files: undefined,
    json: [
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object]
    ]
  }
}
node:events:505
      throw er; // Unhandled 'error' event
      ^

Object
    at SequentialHandler.runRequest (C:\Users\HOST\Documents\GitHub\life-pv\node_modules\@discordjs\rest\dist\lib\handlers\SequentialHandler.cjs:280:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SequentialHandler.runRequest (C:\Users\HOST\Documents\GitHub\life-pv\node_modules\@discordjs\rest\dist\lib\handlers\SequentialHandler.cjs:162:16)
    at async SequentialHandler.queueRequest (C:\Users\HOST\Documents\GitHub\life-pv\node_modules\@discordjs\rest\dist\lib\handlers\SequentialHandler.cjs:99:14)
    at async REST.request (C:\Users\HOST\Documents\GitHub\life-pv\node_modules\@discordjs\rest\dist\lib\REST.cjs:52:22)
    at async GuildInviteManager._fetchMany (C:\Users\HOST\Documents\GitHub\life-pv\node_modules\discord.js\src\managers\GuildInviteManager.js:158:18)
    at async Object.execute (C:\Users\HOST\Documents\GitHub\life-pv\events\basics\ready.js:231:26)
Emitted 'error' event on Client instance at:
    at emitUnhandledRejectionOrErr (node:events:384:10)
    at processTicksAndRejections (node:internal/process/task_queues:85:21) {
  status: 502,
  method: 'GET',
  url: 'https://discord.com/api/v10/guilds/770003066467778590/invites',
  requestBody: { files: undefined, json: undefined }
}
C:\Users\HOST\Documents\GitHub\life-pv\node_modules\@discordjs\rest\dist\lib\handlers\SequentialHandler.cjs:280
      throw new HTTPError.HTTPError(res.constructor.name, status, method, url, requestData);
            ^

Object
    at SequentialHandler.runRequest (C:\Users\HOST\Documents\GitHub\life-pv\node_modules\@discordjs\rest\dist\lib\handlers\SequentialHandler.cjs:280:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SequentialHandler.runRequest (C:\Users\HOST\Documents\GitHub\life-pv\node_modules\@discordjs\rest\dist\lib\handlers\SequentialHandler.cjs:162:16)
    at async SequentialHandler.queueRequest (C:\Users\HOST\Documents\GitHub\life-pv\node_modules\@discordjs\rest\dist\lib\handlers\SequentialHandler.cjs:99:14)
    at async REST.request (C:\Users\HOST\Documents\GitHub\life-pv\node_modules\@discordjs\rest\dist\lib\REST.cjs:52:22)
    at async WebSocketManager.connect (C:\Users\HOST\Documents\GitHub\life-pv\node_modules\discord.js\src\client\websocket\WebSocketManager.js:139:9)
    at async Client.login (C:\Users\HOST\Documents\GitHub\life-pv\node_modules\discord.js\src\client\Client.js:232:7) {
  status: 502,
  method: 'GET',
  url: 'https://discord.com/api/v10/gateway/bot',
  requestBody: { files: undefined, json: undefined }
}
Object
    at SequentialHandler.runRequest (C:\Users\HOST\Documents\GitHub\life-pv\node_modules\@discordjs\rest\dist\lib\handlers\SequentialHandler.cjs:280:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SequentialHandler.runRequest (C:\Users\HOST\Documents\GitHub\life-pv\node_modules\@discordjs\rest\dist\lib\handlers\SequentialHandler.cjs:162:16)
    at async SequentialHandler.runRequest (C:\Users\HOST\Documents\GitHub\life-pv\node_modules\@discordjs\rest\dist\lib\handlers\SequentialHandler.cjs:162:16)
    at async SequentialHandler.runRequest (C:\Users\HOST\Documents\GitHub\life-pv\node_modules\@discordjs\rest\dist\lib\handlers\SequentialHandler.cjs:162:16)
    at async SequentialHandler.queueRequest (C:\Users\HOST\Documents\GitHub\life-pv\node_modules\@discordjs\rest\dist\lib\handlers\SequentialHandler.cjs:99:14)
    at async REST.request (C:\Users\HOST\Documents\GitHub\life-pv\node_modules\@discordjs\rest\dist\lib\REST.cjs:52:22) {
  status: 503,
  method: 'PUT',
  url: 'https://discord.com/api/v10/applications/944592494337876028/guilds/770003066467778590/commands',
  requestBody: {
    files: undefined,
    json: [
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object]
    ]
  }
}
```

**Comment by Jiralite** [comment]
This has nothing to do with discord-api-types. The error code would indicate it's an issue with Discord, so out of our control.
