### ISSUE TITLE
AutoMod Trigger Type Limit Error

### ISSUE THREAD

**Issue by kernelxion** [discordjs/discord-api-types#853]
### Feature

I tried to reach the limit and i got the error

`DiscordAPIError[50035]: Invalid Form Body
0[AUTO_MODERATION_MAX_RULES_OF_TYPE_EXCEEDED]: Maximum number of rules with trigger type 1 is 6
    at handleErrors (C:\Users\USER\Desktop\discordbot\node_modules\@discordjs\rest\dist\index.js:722:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SequentialHandler.runRequest (C:\Users\USER\Desktop\discordbot\node_modules\@discordjs\rest\dist\index.js:1120:23)
    at async SequentialHandler.queueRequest (C:\Users\USER\Desktop\discordbot\node_modules\@discordjs\rest\dist\index.js:953:14)
    at async _REST.request (C:\Users\USER\Desktop\discordbot\node_modules\@discordjs\rest\dist\index.js:1266:22)
    at async AutoModerationRuleManager.create (C:\Users\USER\Desktop\discordbot\node_modules\discord.js\src\managers\AutoModerationRuleManager.js:118:18)`
    
    but the problem is i couldnt find in here
    https://discord-api-types.dev/api/discord-api-types-rest/common/enum/RESTJSONErrorCodes

### Ideal solution or implementation

Can someone push to website :)

**Comment by Jiralite** [comment]
Are you looking for error code 50035? It's already present:
https://discord-api-types.dev/api/discord-api-types-rest/common/enum/RESTJSONErrorCodes#InvalidFormBodyOrContentType

**Comment by kernelxion** [comment]
Oh ok!
